#  File ActiGlobe/R/TAdjust.R
#
#  Copyright (C) 2025  C. William Yao, PhD
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#' @title Adjust Time Shift based on Travel Log
#'
#' @description
#' `TAdjust()` is a function that corrects data points and time-shift based on
#' travelling log. Note that it is important to ensure that the UTC-offset
#' value is correct. When in doubt, please use the UTC function or consult IANA
#' table in the package \code{data(IANA)}. Daylight saving will not be
#' reassessed as in \code{\link{BriefSum}}.
#'
#'
#' @details
#' This function modifies the meta data of the recording generated by
#' \code{\link{BriefSum}}. Based on the travel log, it will adjust the time
#' shift based on the UTC offset values provided. If information about local
#' practice of daylight saving time is provided in the travel log, it will be
#' preserved by \code{TAdjus} during adjustment. When left unspecified, the
#' function will make assumption based on the UTC offset via
#' \code{\link{UTCwDST}}. For latter, daylight saving time is prioritized if
#' there is any possibility of time change due to daylight saving among time
#' zones with UTC offsets. Note that while this fallback strategy may not
#' affect by travels between certain UTCs time zones (e.g., UTC+08:00, +10:00,
#' -09:30, etc.), it may risk over/under-adjust post-travel recording by an
#' hour, otherwise. When in doubt, we recommend avoiding comparisons of pre-
#' and post-travel data.
#'
#'
#' @param Bdf A \code{\link{BriefSum}} object containing per-day metadata for
#' the recording.
#' @param Bdf `r lifecycle::badge("deprecated")` Use `Meta` instead.
#' @param Meta A \code{\link{BriefSum}} object containing per-day metadata for
#' the recording.
#' @param TLog A structured travel log containing date of travel and local time
#' zone. Use `TravelLog()` to generate template.
#' @param TZ The time zone when the recording started. Default is "NULL", which
#'  use the initial geographical location-based time zone indicator specified
#'  in the Bdf. If "local", it will use the local time zone of the computer.
#'  If specified as a time zone string, it will use the specified time zone.
#' @param fork Deprecated. Logical, if TRUE, it will use parallel processing
#' to speed up the computation. Default is FALSE.
#'
#'
#' @return A \code{\link{BriefSum}} object with adjusted data points and time
#' shift based on travel log.
#'
#'
#' @seealso \code{\link{TravelLog}}
#'
#'
#' @examples
#' \donttest{
#' # Create quick summary of the recording with adjustment for daylight saving.
#' ## For more information about FlyEast dataset, please refer to the
#' ## documentation of the dataset or the ActiGlobe online tutorials.
#'
#' BdfList <- BriefSum (
#'     data = FlyEast,
#'     SR = 1 / 60,
#'     Start = "2017-10-19 13:45:00",
#'     TZ = 'America/New_York'
#' )
#'
#' # Extract only the summary report
#' Bdf <- BdfList$Bdf
#'
#'
#' # Adjust time shift based on travel log
#' Bdf.adj <- TAdjust (Bdf  = Bdf,
#'                     TLog = TLog, # sample travel log
#'                     TZ   = 'America/New_York')
#'
#' print (Bdf)
#' print (Bdf.adj)
#' }
#'
#'
#' @keywords Adjust Actigraphy
#' @export



# Strategy:
# Type 1: Non-DST ---> Non-DSTs
# Type 2: DST ---> Non-DSTs
# Type 3: DST ---> Non-DSTs ---> DST

# Security Risk:


TAdjust <- function (Bdf, TLog, TZ = NULL, fork = FALSE) {
    # Step 0. Check Point and Input Validation -------------------------
    # Establish initial time zone ----------------
    if (is.null (TZ)) {
        TZ <- Bdf$TZ_code [1]

    } else if (TZ == "local") {
        TZ <- Sys.timezone ()

    } else {
        TZ <- ValInput (TZ, type = "TZ")
    }


    iUTC <- TZ2UTC (Date = Bdf$Date, TZ = TZ)

    ## Extract Essential Parameters ----------------
    Ds <- Bdf$Date

    Epc <- Bdf$Epoch
    SR  <- 1 / Epc
    FDP <- SR * 3600 * 24 # Total data points per 24 hours

    UTCs <- Bdf$UTC
    aDST <- Bdf$Daylight_Saving
    RS   <- Bdf$Recording_Start
    RE   <- Bdf$Recording_End
    GL0  <- Bdf$GL_Offset
    nDP  <- Bdf$nDataPoints

    # a <- Bdf$Cumulative_Start_Second
    b    <- Bdf$Cumulative_End_Second
    LstP <- max (b)
    # Exc <- Bdf$Excluded
    # Wrn <- Bdf$Warning

    # Step 1. Extract Parameters from Travel Log ------------
    D <- DateFormat (TLog$Date_Start)
    if (any (!D %in% Ds)) {
        D2k  <- which (D %in% Ds)
        TLog <- TLog [D2k, ]
        D    <- DateFormat (TLog$Date_Start, as.date = TRUE)
    }


    P <- R2P (
        Bdf     = Bdf,
        Ds      = D,
        U       = TLog$UTC_Offset,
        has.DST = TLog$Country_with_Daylight_Saving
    )


    Prd   <- P$Prd
    U     <- P$UTC
    aH2J  <- P$H2J
    pUDST <- P$hsDST



    # Step 2. Adjust Time Shift based on Travel Log ------------
    ### Determine if the original UTC from BriefSum is the same as the new UTC
    ###  from R2P
    SameUTC <- UTCs == U

    ### New logical indicator of whether daylight saving occurs...
    nuUDST <- ifelse (SameUTC, aDST, pUDST)

    ### If TZ is not specified, guess it.
    Us  <- UTC2Num (U)
    GMT <- ifelse (Us < 0, "Etc/GMT+", "Etc/GMT")
    gTZ <- paste0 (GMT, -1*Us)


    ### Step 3 Change NDPs ----------------------
    #### Based on the new daylight saving, we will change the NDPs and
    #### cumulative time...
    ##### Adjusting factor for incorrect initial GL guesses
    A1 <- ifelse (nuUDST & GL0 == 0, 0, -1 * GL0)
    GL <- GL0 + A1 ### Update GL....
    #####  Remove the inappropriately adjusted gain or loss due to suspected
    #####  time shift
    NDP <- ifelse (A1 == 0, nDP, nDP + (A1 * 3600 / Epc))
    ##### Number of data points needed to be added.
    mDP <- max (cumsum (nDP)) - max (cumsum (NDP))

    #####  Add the remnant to the last day. Leave the question whether it is
    #####  more than one fDP to later step.
    NDP [length (NDP)] <- NDP [length (NDP)] + mDP


    ### Step 3.2 Edit cumulative time based on NDPs
    a1 <- cumsum ((c (1, NDP [-length (NDP)])) * Epc) # Line 134 from  BriefSum
    b1 <- cumsum (NDP * Epc) # Line 135 from  BriefSum


    ################## Adjust based on Traveling #####################

    ### If U from R2P is the same as the original then H2J to 0
    H2J <- ifelse (SameUTC, 0, aH2J)


    ## Adjust DataPoint ------------------------
    P2J <- H2J * 3600


    ### Adjust Cumulative Start DataPoint ------------
    x <- a1 + P2J
    x [x > LstP] <- NA


    ### Adjust Cumulative End DataPoint ------------
    y <- b1 + P2J
    y [y > LstP] <- NA


    ## Adjust Cumulative Start DataPoint V2 will give you the same as the above
    #  if ( Version == 2) {
    #    T2A = c(0,diff(H2J))
    #    x = a1
    #    y = b1
    #    STR = which(!T2A == 0)
    #    for (nr in STR) {
    #      x[nr:length(x)] = x[nr:length(x)] + T2A[[nr]]*3600
    #      y[nr:length(y)] = y[nr:length(y)] + T2A[[nr]]*3600
    #    }
    #  }


    ### Adjust Daily Data Point ------------
    Sec <- y - x
    N <- 1 + (Sec / Epc) #### Plus one for the End

    ### Step 3.3 Check the Last Da
    Idxl <- length (Ds)
    Nl <- as.integer (N [Idxl]) #### Last number of data
    Dl <- Ds [Idxl] #### Last date of the recording

    ### The starting second of the last day in number
    Tl <- as.numeric (as.POSIXct (Dl, tz = gTZ [Idxl]))

    Epl <- as.numeric (Epc [[1]])
    Timel <- seq (
        from = Tl,
        by = Epl,
        length.out = Nl
    ) #### All time points on the last day.


    HMSl  <- as.POSIXct (Timel, tz = gTZ [Idxl])
    Datel <- suppressWarnings (DateFormat (HMSl)) ### Extract all the dates
    #### Check the numbers of the unique date spanning for the last day.
    uniDl <- unique (Datel)

    ### Find the last time point of the last day.
    TPl <- max (which (Datel %in% Dl))
    REl <- HMSl [TPl]
    RE [Idxl] <- format (REl, "%H:%M:%S") ### Last Time point

    ##### In the rare event when there is more data points on the last day than
    ##### allowed....
    if (length (uniDl) > 1) {
        Nl2 <- Nl - FDP [Idxl] ### Additional Date Points to be relocated


        #### The OCD double check flow control...
        if (Nl2 > 0) {
            N [Idxl] <- FDP [Idxl]
            ### Update the total data point on the last day

            ### Extract the Max cumulative end second for the recording
            yMax <- y [Idxl]

            #### Update the cumulative end second on the last day
            y [Idxl] <- y [Idxl] - Nl2 * Epc [Idxl]

            #### New Last Day
            Ds [Idxl + 1] <- as.character (as.Date (Ds [Idxl]) + 1)
            Epc [Idxl + 1] <- Epc [Idxl]
            ### Assume the same epoch length as the last

            U [Idxl + 1] <- U [Idxl] ### Assume the same UTC as the last
            gTZ [Idxl + 1] <- gTZ [Idxl] ### Assume the same TZ as the last
            nuUDST [Idxl + 1] <- DST (
                Date = Ds [Idxl + 1],
                TZ   = gTZ [Idxl]
            ) ### Check if DST occur
            RS [Idxl + 1] <- RS [Idxl]
            ### Assume the same begining time as the last

            ### Extract the New last time of recording
            RE [Idxl + 1] <- format (HMSl [length (HMSl)], "%H:%M:%S")
            ### Check GL due to DST
            GL [Idxl + 1] <- DST2GL (Date = as.POSIXct (Ds [Idxl + 1],
														tz = gTZ [Idxl]))
            N [Idxl + 1] <- Nl2 ### Cumulative data points on the NEW last day
            ### Cumulative start second on the NEW last day
            x [Idxl + 1] <- y [Idxl] + Epc [Idxl]
            y [Idxl + 1] <- yMax ### Cumulative end second on the NEW last day
            ### Assume the same recording period as the last
            Prd [Idxl + 1] <- Prd [Idxl]
            H2J [Idxl + 1] <- H2J [Idxl]
            ### Assume the same hour to adjust as the last
        }
    }




    # Step 4. Amend updates back to the report ----------------
    ln <- length (Ds)
    ##  Initialize Report ------------
    Summary <- data.frame (matrix (nrow = ln,
                                   ncol = length (names (Bdf))))
    names (Summary) <- names (Bdf)
    Summary$Date    <- Ds
    Summary$Epoch   <- Epc
    Summary$UTC     <- U
    Summary$TZ_code <- gTZ
    Summary$Daylight_Saving <- nuUDST
    Summary$Recording_Start <- RS
    Summary$Recording_End   <- RE
    Summary$GL_Offset       <- GL

    #### Data Points and Summary
    Summary$nDataPoints <- N
    Summary$Cumulative_Start_Second <- x
    Summary$Cumulative_End_Second   <- y


    ### Warning and Exclusion ------------
    ##### Initiation
    Summary$Warning  <- ""
    Summary$Excluded <- FALSE

    ##### Remove Missing days
    Summary$Warning [is.na (y)]  <- "Removed after adjustment"
    Summary$Excluded [is.na (y)] <- TRUE

    ##### Label Travel Days
    Summary$Warning [Summary$Date %in% D]  <- "Travel Day"
    Summary$Excluded [Summary$Date %in% D] <- TRUE

    D <- as.Date (D)

    Summary$Warning [Summary$Date %in% (D - 1)] <- "Day Before Travel"
    ### To ensure only adding a proper label to the day after travelling.
    D2 <- D [grep ("Travel", Bdf$Warning [Bdf$Date %in% D])]
    Summary$Warning [Summary$Date %in% (D2 + 1)] <- "Day After Travel"


    ##### Label Incomplete
    if (length (FDP) < length (Summary$nDataPoints)) {
        FDP <- rep (FDP [[1]], length (Summary$nDataPoints))
    }

    Summary$Warning [Summary$nDataPoints < FDP]  <- "Incomplete Recording"
    Summary$Excluded [Summary$nDataPoints < FDP] <- TRUE

    if (length (uniDl) > 1) {
        ### Update the warning on the last day
        Summary$Warning [Idxl]  <- "Original Last Day"
        Summary$Excluded [Idxl] <- FALSE
        ### Update the exclusion on the last day
    }

    Summary$Recording_Period <- Prd
    Summary$Hour_Adjusted    <- H2J

    ## Warning for time change due to daylight saving
    if (any (nuUDST)) {
        message ("
Time change due to daylight saving occured at the local time zone.")
    }


    # Step 5. Validate Dates -------------------



    class (Summary) <- c ("ActiGlobe", "data.frame")
    return (Summary)
}





#' @title Readjust Bdf after realignment of timeshift
#'
#' @description
#' This helper function takes the initial realigned data points from Step 3
#'
#'
#' @param Bdf A \code{\link{BriefSum}} object containing per-day metadata for
#' the recording.
#' @param H2J A numeric vector of hours to adjust for each day, which is the
#' output from Step 3 of \code{\link{TAdjust}}. It indicates the number of hours to
#' adjust for each day based on the travel log and time shift.
#' @param pUDST A logical vector indicating whether daylight saving time is
#' observed for each day based on the travel log. It is generated by
#' \code{\link{R2P}}.
#'
#' @return A \code{\link{BriefSum}} object with adjusted date and essential
#' amendments if needed.
#'
#' @noRd

pAdjFiller <- function (Bdf, H2J, pUDST) {
    # Step 0. Extract Parameters -------------------------
    Epc <- Bdf$Epoch [[1]]
    Ds  <- as.numeric (as.Date (Bdf$Date))
    a   <- Bdf$Cumulative_Start_Second
    b   <- Bdf$Cumulative_End_Second
    ln  <- length (a)

    # Step 1. Identify non-allocated and overlap ---------------
    CkP <- c (0, diff (H2J))
    Unaloc <- which (CkP > 0)  ### Non-allocated time points
    Ovlap  <- which (CkP < 0)  ### Overlaps time points



    if (length (Unaloc) > 0 || length (Ovlap) > 0) {

    # Step 2. Inject New Row Forward Adjustment -----------
    if (length (Unaloc) > 0) {
    oRwID <- seq (1L, nrow (Bdf))
    adNum <- cumsum (rep (1L, length (Unaloc))) - 1
    Rinj  <- Unaloc + adNum # Also serve as the new non-allocated row ID

    pUDST1 <- pUDST
    nRwID  <- oRwID
    CkP1   <- CkP
    Ds1    <- Ds
    a1     <- a
    b1     <- b
    for (x in Rinj) {
        xn1 <- x - 1L

        pUDST1 <- append (pUDST1, values = pUDST [xn1], after = xn1)
        nRwID  <- append (nRwID, values = NA, after = xn1)
        CkP1   <- append (CkP1, values = 0, after = xn1)
        Ds1    <- append (Ds1, values = Ds1 [xn1] + 1, after = xn1)
        a1     <- append (a1, values = b1 [xn1] + Epc, after = xn1)
        b1     <- append (b1, values = a1 [x + 1L] - Epc, after = xn1)
    }


    nDP <- ((b1 - a1) / Epc) + 1


    nln  <- length (nRwID)
    DAdj <- numeric (nln)

    ## Hours to adjust for the non-allocated rows.
    ## It is the recording period of the non-allocated rows
    ## plus the hour to adjust for the subsequent day.
    Hd12 <- (nDP * Epc / 3600) [Rinj] + CkP1 [Rinj + 1]
    DAdj [Rinj + 1L] <- ifelse (Hd12 >= 24, 1, 0)
    DAdj <- cumsum (DAdj)
    Ds1  <- as.Date (Ds1 + DAdj)

    ### Prepare updated Bdf with new rows
    nBdf <- as.data.frame (matrix (nrow = nln,
                                   ncol = length (Bdf)))
    names (nBdf) <- names (Bdf)
    nBdf [!is.na (nRwID), ] <- Bdf

    # Inherit the subsequent rows for non-allocated rows
    TVNames  <- c ("Epoch","UTC","TZ_code","Recording_Start",
                   "Recording_Period")
    nBdf [Rinj, TVNames]  <- nBdf [Rinj - 1, TVNames]

    TVNames1 <- c ("Warning","Excluded")
    nBdf [Rinj, TVNames1] <- nBdf [Rinj + 1, TVNames1]

    # Update date
    nBdf$Date <- Ds1
    # Amend Additional Info ----------------
    ## Update Recording and Cumulative Time and nDataPoints
    TVNames2 <- c ("nDataPoints","Cumulative_Start_Second",
                   "Cumulative_End_Second")
    nBdf [TVNames2] <- cbind (nDP, a1, b1)

    nBdf$Hour_Adjusted <- CkP1

    ## Daylight saving
    pUDST1 [Rinj] <- pUDST1 [Rinj - 1]
    DST (DT = Ds1 [Rinj], TZ = nBdf$TZ_code [Rinj])


    } else {
        nBdf <- Bdf
        Rinj <- NA
        a1   <- a
        b1   <- b
        CkP1 <- CkP
        nln  <- ln
    }

    # Step 3. Extract Parameters -------------------------
    Ds2  <- nBdf$Date
    U2   <- nBdf$UTC
    TZ2  <- nBdf$TZ_code
    GL2  <- nBdf$GL_Offset
    nDP2 <- nBdf$nDataPoints

    ## Additional Parameters
    Ovlap2 <- which (CkP1 < 0) ### Overlaps time points
    nln2   <- length (Ds2)

    # Step 4. Compute Date Adjustment Backward ---------------
    ### Compute the adjustment for the cumulative date points
    DAdj2  <- numeric (nln2)
    Hd21   <- CkP1 [Ovlap2] * 2
    DAdj2 [Ovlap2 - 1L] <- ifelse (Hd21 <= -24, -1, 0)
    DAdj2  <- cumsum (DAdj2)
    Ds2    <- as.Date (Ds2 + DAdj2)

    nBdf$Date <- Ds2

    # Step 5. Determine Daylight saving time ----------------





    } else {

        return (Bdf)

    }



    # Step 5. Compute end of recording ----------------
    RE <- vapply (Rinj, function (x)
        as.numeric (as.POSIXlt (Ds [x], tz = TZ [x])) + (nDP [x] - 1) * Epc,
        numeric (1))

    RE <- vapply (seq_len (length (Rinj)), function (x)
        as.character (as.POSIXlt (RE [x], tz = TZ [x])),
        character (1))

    RE <- TimeFormat (RE, as.time = TRUE)



    for (i in seq_along (Ini)) {
        x <- Ini [i]:nln
        DAdj [x] <- DAdj [x] + TAdd [i]
    }



    # Step 4. Adjust Date  ---------------
    Ds [Rinj] <- Ds [Rinj + 1L]
    DsN <- as.numeric (as.Date (Ds))


    for (i in seq (length (Ini)) ){
        nBdf$Date [Ini [i]:End [i]] <-
            as.Date (DsN [Ini [i]:End [i]] + Mtplr [i])
    }






    # Step 4. Adjsut Date Points ---------------










    # Step 2. Adjust Date based on Cumulative Time and Epoch ------------
    DT_adj <- as.Date (Ds [1]) + (a / (3600 * 24))

    # Step 3. Create Adjusted BriefSum Object ------------
    Summary <- nBdf
    Summary$Date  <- Ds2
    Summary$Epoch <-
    Summary$UTC   <-
    Summary$TZ_code     <- TZ
    Summary$GL_Offset   <- GL
    Summary$nDataPoints <- nDP
    Summary$Cumulative_Start_Second <- a
    Summary$Cumulative_End_Second <- b

    class (Summary) <- c ("ActiGlobe", "data.frame")
    return (Summary)
}

