#  File ActiGlobe/R/write.cosinor.R
#
#  Copyright (C) 2025  C. William Yao, PhD
#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#
#
#' @title Generate Report for Daily Cosinor and Generate Summary Plot
#'
#' @description
#' `write.cosinor()` is a multi-wrapper function which generate cosinor plot using CosinorM and data trend using `geom_smooth`. All daily results could be found in the exported report.
#'
#'
#'
#' @import gridExtra ggplot2 grDevices utils stats
#' @param Dir The directory where the recordings to be exported <e.g. "C:/Users/___YOUR USERNAME___/UPSTREAM FOLDER/.../FOLDER NAME/">
#' @param ID The subject's ID which would be used to create a folder.
#' @param DailyAct A data.frame list generated by `Act2Daily()`
#' @param Bdf The summary report created by BriefSum.
#' @param VAct The name of the variable containing activity score  (default assumed the second variable)
#' @param VTm The name of the variable containing the time coordiante (default assumed the first variable)
#' @keywords Export Actigraphy Cosinor Trend
#' @examples
#' \dontrun{
#'
#' # Import data
#' data(FlyEast)
#'
#'
#' # Create quick summary of the recording with adjustment for daylight saving.
#' BdfList <-
#' BriefSum(df = FlyEast ,
#'          SR = 1/60,
#'          Start = "2017-10-24 13:45:00")
#'
#'
#'  # Let's extract the quick summary of the recording
#' Bdf <- BdfList$Bdf
#'
#' ### Note that since the original data was affected by travel-induced time
#' ### shift, the recordings would not be properly segmented from 2017-11-02.
#'
#' ## To avoid time shift due to travelling, we will keep only the first 8 days.
#' Bdf <- Bdf[1:8,]
#'
#'
#' ## Segment Data by Day
#' dfList =
#'  Act2Daily(df = FlyEast,
#'            Bdf = Bdf,
#'            VAct = "Activity",
#'            VTm = "X2",
#'            Incomplete = TRUE,
#'            Travel = TRUE)
#'
#'
#' ## Generate graphic summary of daily recordings in pdf with an addition
#' ## `Summary` file just like write.act
#'  write.cosinor(Dir = getwd(), ## Export to the current working directory
#'                ID = "JD",
#'                df = dfList$Daily_df,
#'                Bdf = Bdf,
#'                VAct = "Activity",
#'                VTm = "Time")
#'
#' ## To see what was exported copy the path generated by the code below and
#' ## paste it as an url in a web browser or the file explorer.
#'  getwd()
#'
#'
#' }
#' @seealso \code{\link{Act2Daily}}
#' @export


write.cosinor = function(Dir, ID, DailyAct, Bdf, VAct = NULL, VTm = NULL){


  ## Get Essential Info -----------------
  D = names(DailyAct)
  U = Bdf$UTC



  #### Initialize all cosinor results -----------------------
  Bdf[c("MESOR","Amplitude","Acrophase","Shift_of_Acrophase")] = NA



  ## Check Directory ----------------
  fDir = paste0(Dir, "/", ID)
  if (!dir.exists(fDir)) dir.create(fDir)



  ## Create a PDF file for the ID  ----------------
  grDevices::pdf(paste0(fDir,"/",ID,".pdf"), onefile = TRUE, paper="a4r")

  ### Plot ----------------
  for (d in D) {

    print(d)
    df = DailyAct[[d]]

    if (!is.null(df)) {
    ##### Get Variable Names -------------
    if (is.null(VTm))  VTm = names(df)[[1]]
    if (is.null(VAct))  VAct = names(df)[[2]]

    names(df) = c("Tm", "Act")
    Tm = as.numeric(df[["Tm"]])
    Act = as.numeric(df[["Act"]])

    #### Get the time zone for the current ID and date
    TZ = U[D == d]



    #### Create activity trend for the top panel ---------------

    Act[is.na(Act)] = 0 #### Just in acse, provide a zero imputation for NA.

    if (all(Act == 0)) {

      top.plot =
        ggplot2::ggplot(df, aes(x = Tm, y = Act)) +
        geom_point(aes(color = 'Original Measure')) +
        geom_line(aes(color = 'Smoothed Trend')) +
        labs(title = d,
             subtitle = TZ,
             x = "Hour",
             y = "Activity") +
        theme(plot.title = element_text(hjust = 0.5)) +
        scale_color_manual(values = c('Original Measure' = 'black',
                                      'Smoothed Trend' = 'blue'),
                           name = "Legend Title") +
        theme_bw()

    } else {

      top.plot =
        ggplot2::ggplot(df, aes(x = Tm, y = Act)) +
        geom_point(aes(color = 'Original Measure')) +
        geom_smooth(aes(color = 'Smoothed Trend')) +
        labs(title = d,
             subtitle = TZ,
             x = "Hour",
             y = "Activity") +
        theme(plot.title = element_text(hjust = 0.5)) +
        scale_color_manual(values = c('Original Measure' = 'black',
                                      'Smoothed Trend' = 'blue'),
                           name = "Legend Title") +
        theme_bw()

    }


    ## Fit cosinor models with 24Hr period ---------------
    m1 = CosinorM(time = Tm, activity = Act, tau = 24)

    Coef = m1$coef.cosinor[1:3]
    Coef[[4]] = Rad2Hr(Coef[[3]], tau = 24)

    # Update the report with cosinor model coefficients
    Bdf[Bdf$Date == d, c("MESOR","Amplitude","Shift_of_Acrophase","Acrophase")] = Coef



    # Create the bottom plot for cosinor models
    bottom.plot <- ggCosinorM(m1, title_extra = d)

    # Arrange the top and bottom plots in a grid
    grid.arrange(top.plot, bottom.plot)

    }
  }

  # Close the PDF file
  dev.off()

  # Write the merged summary report to a CSV file
  message("Updating the summary file")
  utils::write.csv(Bdf, paste0(fDir,"/Summary.csv"), row.names = F)


}

